apiVersion: meows.cybozu.com/v1alpha1
kind: RunnerPool
metadata:
  name: runnerpool2
spec:
  repositoryName: github-actions-controller-ci
  replicas: 3
  setupCommand:
  - "bash"
  - "-c"
  - "date > /tmp/test"
  slackAgent:
    serviceName: slack-agent.meows.svc
    channel: "#test2"
  template:
    image: meows-runner:kindtest
    imagePullPolicy: Never
    env:
    - name: EXTEND_DURATION
      value: "30s"
