apiVersion: actions.cybozu.com/v1alpha1
kind: RunnerPool
metadata:
  name: runnerpool-sample
spec:
  repositoryName: repository-sample
  replicas: 3
  slackAgent:
    serviceName: slack-agent
  template:
    image: actions-runner:latest
