apiVersion: meows.cybozu.com/v1alpha1
kind: RunnerPool
metadata:
  name: runnerpool1
spec:
  repositoryName: meows-ci
  replicas: 3
  slackAgent:
    serviceName: slack-agent.meows.svc
  template:
    metadata:
      labels:
        test-label: test
      annotations:
        test-annotation: test
    image: meows-runner:kindtest
    imagePullPolicy: Never
    env:
    - name: EXTEND_DURATION
      value: "30s"
